### ISSUE TITLE
Issues with anki 2.1.34 when i click add card on a new card window

### ISSUE THREAD

**Issue by aPaci95** [Arthur-Milchior/anki-keep-model-in-add-cards#7]
Debug info:
Anki 2.1.34 (8af8f565) Python 3.8.0 Qt 5.15.1 PyQt 5.15.1
Platform: Windows 10
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-09-30 15:51:00

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 493, in handler
  File "aqt\editor.py", line 483, in <lambda>
  File "C:\Users\pacia\Desktop\AnkiFolder\ankidata\addons21\424778276\addCards.py", line 67, in _addCards
    self.editor.saveAddModeVars()
  File "aqt\editor.py", line 595, in saveAddModeVars
  File "anki\notes.py", line 87, in model
  File "anki\models.py", line 174, in get
  File "anki\rsbackend_gen.py", line 426, in get_notetype_legacy
  File "anki\rsbackend.py", line 262, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

**Comment by Arthur-Milchior** [comment]
Thanks.
I'll need to take a look eventuall. I'm really sorry but until then, I fear you'll have to deactivate the add-on

**Comment by aPaci95** [comment]
Sorry if i disturb you, did you have a chance to take a look?
