### ISSUE TITLE
Causes error in Anki 2.1.41

### ISSUE THREAD

**Issue by ghost** [Arthur-Milchior/anki-keep-model-in-add-cards#9]
I just updated to Anki 2.1.41 and keep getting an error when I change the note type in the add window. Disabling the add-on fixes the issue, but then, of course, I no longer have the ability to have one note type per add window.

**Comment by aPaci95** [comment]
I get the same error whenever i try to change the note type

Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-23 12:15:45

Caught exception:
Traceback (most recent call last):
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\424778276\modelChooser.py", line 22, in onModelChange
    ret = StudyDeck(
  File "aqt\studydeck.py", line 41, in __init__
TypeError: QDialog(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'builtin_function_or_method'

**Comment by ijgnd** [comment]
you can fix this by applying these changes: https://github.com/Arthur-Milchior/anki-keep-model-in-add-cards/pull/10/commits/21618eea5a62e74909fa4b42792f04095d48c840

the real fix for 2.1.41+ is one character in one line: change `parent=self.widget,` to `parent=self._widget,` in the file modelChooser.py  from this add-on.

**Comment by huandney** [comment]
> you can fix this by applying these changes: [21618ee](https://github.com/Arthur-Milchior/anki-keep-model-in-add-cards/commit/21618eea5a62e74909fa4b42792f04095d48c840)
> 
> the real fix for 2.1.41+ is one character in one line: change `parent=self.widget,` to `parent=self._widget,` in the file modelChooser.py from this add-on.

Thanks this works on 2.1.44.

**Comment by aPaci95** [comment]
@Arthur-Milchior  could you please push the fix in ankiweb?
